name: Release

on:
  workflow_dispatch:
    inputs: 
      versionBump:
        description: The type of version bump (major/minor/patch)
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
permissions:
  contents: write

jobs:
  versionBump:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semver_tag.outputs.new_version }}
      new_version_raw: ${{ steps.semver_tag.outputs.new_version_raw }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Semver tag
        id: semver_tag
        run: |
          last_tag=$(git describe --tags --always --abbrev=0)
          new_version=$(./semver.sh "$last_tag" "${{ inputs.versionBump }}")
          new_version_raw=${new_version#v}

          echo "${{ inputs.versionBump }} bump from $last_tag to $new_version"
          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
          echo "new_version_raw=$new_version_raw" >> "$GITHUB_OUTPUT"
      
      - name: Push new tag
        run: |
          git tag ${{ steps.semver_tag.outputs.new_version }} HEAD
          git push origin --tags




  publish:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            rid: linux-x64
            artifact:
              from: PKHeX.CLI
              to: pkhex-cli
          - os: windows-latest
            rid: win-x64
            artifact:
              from: PKHeX.CLI.exe
              to: pkhex-cli.exe
          - os: macos-latest
            rid: osx-arm64
            artifact:
              from: PKHeX.CLI
              to: pkhex-cli
          - os: macos-latest
            rid: osx-x64
            artifact:
              from: PKHeX.CLI
              to: pkhex-cli

    runs-on: ${{ matrix.config.os }}
    needs: versionBump

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Update submodules to the latest commit
        run: |
          git submodule update --remote --recursive
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Publish - ${{ matrix.config.rid }}
        run: dotnet publish ./src/PKHeX.CLI/PKHeX.CLI.csproj -r ${{ matrix.config.rid }} -c Release /p:Version=${{ needs.versionBump.outputs.new_version_raw }}

      - name: Copy artifact with new name
        run: cp ./src/PKHeX.CLI/bin/Release/net8.0/${{ matrix.config.rid }}/publish/${{ matrix.config.artifact.from }} ./src/PKHeX.CLI/bin/Release/net8.0/${{ matrix.config.rid }}/publish/${{ matrix.config.artifact.to }}

      - name: Upload - ${{ matrix.config.rid }}
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.config.rid }}
          path: ./src/PKHeX.CLI/bin/Release/net8.0/${{ matrix.config.rid }}/publish/${{ matrix.config.artifact.to }}

  release:
    runs-on: ubuntu-latest
    needs: [versionBump, publish]
    
    outputs:
      osx_arm64_sha256: ${{ steps.sha256.outputs.osx_arm64_sha256 }}
      osx_x64_sha256: ${{ steps.sha256.outputs.osx_x64_sha256 }}
      linux_x64_sha256: ${{ steps.sha256.outputs.linux_x64_sha256 }}
      win_x64_sha256: ${{ steps.sha256.outputs.win_x64_sha256 }}

    permissions:
      contents: write

    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: List artifacts
        run: ls -R artifacts
      - name: Zip artifacts
        run: |
          zip -j pkhex-cli-linux-x64.zip artifacts/artifact-linux-x64/pkhex-cli
          zip -j pkhex-cli-win-x64.zip artifacts/artifact-win-x64/pkhex-cli.exe
          zip -j pkhex-cli-osx-arm64.zip artifacts/artifact-osx-arm64/pkhex-cli
          zip -j pkhex-cli-osx-x64.zip artifacts/artifact-osx-x64/pkhex-cli

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          tag_name: ${{ needs.versionBump.outputs.new_version }}
          files: |
            pkhex-cli-linux-x64.zip
            pkhex-cli-win-x64.zip
            pkhex-cli-osx-arm64.zip
            pkhex-cli-osx-x64.zip
            
      - name: Output SHA256
        id: sha256
        run: |
          # Compute SHA256 checksums
          OSX_ARM64_SHA256=$(sha256sum pkhex-cli-osx-arm64.zip | awk '{ print $1 }')
          OSX_X64_SHA256=$(sha256sum pkhex-cli-osx-x64.zip | awk '{ print $1 }')
          LINUX_X64_SHA256=$(sha256sum pkhex-cli-linux-x64.zip | awk '{ print $1 }')
          WIN_X64_SHA256=$(sha256sum pkhex-cli-win-x64.zip | awk '{ print $1 }')
  
          # Export checksums as environment variables
          echo "osx_arm64_sha256=${OSX_ARM64_SHA256}" >> $GITHUB_ENV
          echo "osx_x64_sha256=${OSX_X64_SHA256}" >> $GITHUB_ENV
          echo "linux_x64_sha256=${LINUX_X64_SHA256}" >> $GITHUB_ENV
          echo "win_x64_sha256=${WIN_X64_SHA256}" >> $GITHUB_ENV
